global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "iot-controller"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["iot-controller:8080"]

  - job_name: "rule-engine"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["rule-engine:8081"]

  - job_name: "rabbitmq"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["rabbitmq:15672"]
