server:
  port: 8081

spring:
  application:
    name: rule-engine
  data:
    mongodb:
      uri: mongodb://mongodb:27017/iot
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.iot.mops: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

app:
  rabbit:
    exchange: iot.events
    queue: iot.events.queue
    routing-key: device.*
  rules:
    window-size: 10
    max-window-age-sec: 60
